In [1]:
import pandas as pd
import glob

In [2]:
path = "C:/Users/gaolg/OneDrive/Área de Trabalho/projetos/ips_nordeste/Indicadores"
csv_files = glob.glob(path + "/**/*.csv", recursive=True)

In [3]:
path_dict = "C:/Users/gaolg/OneDrive/Área de Trabalho/projetos/ips_nordeste/Dicionario, Documentanção e Codigos/dicionario_regioes.csv"
dicionario = pd.read_csv(path_dict)
dicionario["cod_municipio"] = dicionario["cod_municipio"].astype(str)
dicio = dicionario[["nome_regiao", "sigla_uf", "nome_municipio", "cod_municipio"]]

dicio = dicio.copy()
dicio["cod_municipio6"] = dicio["cod_municipio"].astype(str).str[:6]
dicio_mini = dicio[["cod_municipio6", "cod_municipio"]]

In [4]:
keys = []
for file in csv_files:
    key = file.split("\\")[-1].split(".")[0]
    keys.append(key)

In [5]:
dataframes = []
for file in csv_files:
    df = pd.read_csv(file)
    dataframes.append(df)

In [6]:
for i, df in enumerate(dataframes):
    df.rename(columns={
        "cod_municipio_6": "cod_municipio",
        "cod_municipio6": "cod_municipio"
    }, inplace=True)

    df["cod_municipio"] = df["cod_municipio"].astype(str)

    if len(df["cod_municipio"][0]) == 6:
        df.rename(columns={"cod_municipio": "cod_municipio6"}, inplace=True)
        df = dicio.merge(df, on="cod_municipio6", how="left")
    else:
        df = dicio.merge(df, on="cod_municipio", how="left")

    if "cod_municipio6" in df.columns:
        df = df.drop(columns=["cod_municipio6"])

    # Update the DataFrame in the list with the modified DataFrame
    dataframes[i] = df

In [7]:
for i, df in enumerate(dataframes):
    if "cod_municipio6" in df.columns:
        df = df.drop(columns=["cod_municipio6"])

    # Update the DataFrame in the list with the modified DataFrame
    dataframes[i] = df

In [8]:
columns_to_check = []
columns_to_remove = ["nome_regiao", "sigla_uf", "nome_municipio", "cod_municipio"]
for df in dataframes:
    column_first = list(set(df.columns.to_list()) - set(columns_to_remove))
    columns_to_check.append(column_first)

In [9]:
import itertools
nan_counts = []
for df, column in zip(dataframes, columns_to_check):
     nan_count = df[column[0]].isnull().sum()
     nan_counts.append(nan_count)

In [10]:
df_nan = pd.DataFrame(list(zip(keys, nan_counts)), columns=["key", "nan_count"])
df_nan.sort_values(by="nan_count", ascending=False)

                             key  nan_count
11              obitos_acidentes       5293
41           violencia_indigenas       4022
24                 obitos_cancer       3944
2             assasinatos_jovens       3304
9                    desnutricao       2920
28                      sucidios       2448
1             assasinatos_gerais       1918
10           doencas_infecciosas       1909
25      obitos_diabetes_mellitus        893
42            violencia_infantil        805
26  obitos_doencas_respiratorias        380
40            violencia_feminina        319
0             abastecimento_agua        258
23  obitos_aparelho_circulatorio        101
15                   subnutricao          6
34      frota_onibus_microonibus          4
36             proporcao_eleitos          2
18       densidade_telefone_fixo          2
33              direitos_humanos          0
32                       cultura          0
31                  acoes_grupos          0
30                        tdi_em          0
29                        tdi_ef          0
37          rais_ensino_superior          0
38                 rais_mulheres          0
39             trabalho_infantil          0
35         gravidez_adolescencia          0
22                          ideb          0
27                 reprovacao_ef          0
21          gases_co2_per_capita          0
20       densidade_tv_assinatura          0
19      densidade_telefone_movel          0
17         densidade_banda_larga          0
16                   abandono_ef          0
14               obitos_gravidez          0
13                  obitos_covid          0
12             obitos_ate_5_anos          0
8            cad_unico_sanitario          0
7                 cad_unico_piso          0
6               cad_unico_parede          0
5                 cad_unico_lixo          0
4           cad_unico_iluminacao          0
3                 cad_unico_agua          0
43       vunerabilidade_familiar          0